packages:
  - services/*
  - packages/*

allowBuilds:
  '@discordjs/opus': true
  '@lng2004/node-datachannel': true
  esbuild: true
  node-av: true
  node-crc: true
  sharp: true
  zeromq: true

minimumReleaseAgeExclude:
  - '@types/node@25.9.0'
  - pg-cloudflare@1.4.0
  - pg-connection-string@2.13.0
  - pg-pool@3.14.0
  - pg-protocol@1.14.0
  - pg@8.21.0
  - tsx@4.22.2
  - '@next/env@16.2.12'
  - '@next/swc-darwin-arm64@16.2.12'
  - '@next/swc-darwin-x64@16.2.12'
  - '@next/swc-linux-arm64-gnu@16.2.12'
  - '@next/swc-linux-arm64-musl@16.2.12'
  - '@next/swc-linux-x64-gnu@16.2.12'
  - '@next/swc-linux-x64-musl@16.2.12'
  - '@next/swc-win32-arm64-msvc@16.2.12'
  - '@next/swc-win32-x64-msvc@16.2.12'
  - lucide-react@1.27.0
  - next@16.2.12
  - shadcn@4.15.0

onlyBuiltDependencies:
  - '@discordjs/opus'
  - '@lng2004/node-datachannel'
  - esbuild
  - node-av
  - sharp
  - zeromq

patchedDependencies:
  node-crc@4.0.0: patches/node-crc@4.0.0.patch
