import {
  DISCORD_ANALYSIS_QUEUE_STATUS,
  DISCORD_ATTACHMENT_CREATED,
  DISCORD_ATTACHMENT_UPLOADED,
  DISCORD_CHANNEL_TOPIC_UPDATED,
  DISCORD_GUILD_MEMBER_ADDED,
  DISCORD_GUILD_MEMBER_REMOVED,
  DISCORD_MESSAGE_ANALYZED,
  DISCORD_MESSAGE_CREATED,
  DISCORD_MESSAGE_DELETED,
  DISCORD_MESSAGE_UPDATED,
  DISCORD_MODERATION_ACTION,
  DISCORD_PRESENCE_UPDATED,
  DISCORD_REACTION_ADDED,
  DISCORD_REACTION_REMOVED,
  DISCORD_THREAD_CREATED,
  DISCORD_THREAD_DELETED,
  DISCORD_THREAD_UPDATED,
  type DiscordGatewayEvent,
} from "../../shared/index.js";

export type { DiscordGatewayEvent };

export const EventChannels = {
  MESSAGE_CREATED: DISCORD_MESSAGE_CREATED,
  MESSAGE_UPDATED: DISCORD_MESSAGE_UPDATED,
  MESSAGE_DELETED: DISCORD_MESSAGE_DELETED,
  MESSAGE_ANALYZED: DISCORD_MESSAGE_ANALYZED,
  ATTACHMENT_CREATED: DISCORD_ATTACHMENT_CREATED,
  ATTACHMENT_UPLOADED: DISCORD_ATTACHMENT_UPLOADED,
  ANALYSIS_QUEUE_STATUS: DISCORD_ANALYSIS_QUEUE_STATUS,
  REACTION_ADDED: DISCORD_REACTION_ADDED,
  REACTION_REMOVED: DISCORD_REACTION_REMOVED,
  THREAD_CREATED: DISCORD_THREAD_CREATED,
  THREAD_DELETED: DISCORD_THREAD_DELETED,
  THREAD_UPDATED: DISCORD_THREAD_UPDATED,
  CHANNEL_TOPIC_UPDATED: DISCORD_CHANNEL_TOPIC_UPDATED,
  PRESENCE_UPDATED: DISCORD_PRESENCE_UPDATED,
  GUILD_MEMBER_ADDED: DISCORD_GUILD_MEMBER_ADDED,
  GUILD_MEMBER_REMOVED: DISCORD_GUILD_MEMBER_REMOVED,
  MODERATION_ACTION: DISCORD_MODERATION_ACTION,
} as const;

export type EventChannelType =
  (typeof EventChannels)[keyof typeof EventChannels];
